/*
 * generated by Xtext
 */
package fr.inria.diverse.docl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DOclRuntimeModule extends fr.inria.diverse.docl.AbstractDOclRuntimeModule {

}
