/*
 * generated by Xtext
 */
package fr.inria.diverse.docl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DOclStandaloneSetup extends DOclStandaloneSetupGenerated{

	public static void doSetup() {
		new DOclStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

