/*
 * generated by Xtext
 */
package fr.inria.diverse.docl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DOclUiModule extends fr.inria.diverse.docl.ui.AbstractDOclUiModule {
	public DOclUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
